trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'

  steps:
  - task: UseNode@2
    inputs:
      version: '14'

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run build
    displayName: 'Build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive build artifacts'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: BuildAndDeploy
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'YourAzureSubscription'
      appName: 'YourWebAppName'
      package: '$(System.ArtifactsDirectory)/drop/$(Build.BuildId).zip'
      deploymentMethod: 'zipDeploy'
